"""environmnet constants for archictecture 1.0.0"""

HOME_ENVIRONMENT_VARIABLE: str = "HOME"

PATH_ENVIRONMENT_VARIABLE: str = "PATH"

SHELL_ENVIRONMENT_VARIABLE: str = "SHELL"

TERM_ENVIRONMENT_VARIABLE: str = "TERM"

USER_ENVIRONMENT_VARIABLE: str = "USER"

TEMP_ENVIRONMENT_VARIABLE: str = "TEMP"

TMP_ENVIRONMENT_VARIABLE: str = "TMP"

LANG_ENVIRONMENT_VARIABLE: str = "LANG"

HOSTNAME_ENVIRONMENT_VARIABLE: str = "HOSTNAME"

__all__: list[str]= [
     "HOME_ENVIRONMENT_VARIABLE",
     "PATH_ENVIRONMENT_VARIABLE",
     "SHELL_ENVIRONMENT_VARIABLE",
     "TERM_ENVIRONMENT_VARIABLE",
     "TMP_ENVIRONMENT_VARIABLE",
     "USER_ENVIRONMENT_VARIABLE",
     "TEMP_ENVIRONMENT_VARIABLE",
     "LANG_ENVIRONMENT_VARIABLE",
     "HOSTNAME_ENVIRONMENT_VARIABLE",
]
